"""empty message

Revision ID: fb39334c6572
Revises: ab7ae8eefd60
Create Date: 2023-05-23 11:02:05.169904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb39334c6572'
down_revision = 'ab7ae8eefd60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('teachworks_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'teachworks_id')
    # ### end Alembic commands ###
