"""empty message

Revision ID: ab7ae8eefd60
Revises: 8d46d052c75b
Create Date: 2023-05-23 10:04:06.994036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7ae8eefd60'
down_revision = '8d46d052c75b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('void_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'void_date')
    # ### end Alembic commands ###
