"""empty message

Revision ID: a6e5b388d015
Revises: 5f8ac330b4c7
Create Date: 2023-06-04 18:59:27.966670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e5b388d015'
down_revision = '5f8ac330b4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('test', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'test')
    # ### end Alembic commands ###
